//
//  BrandsList.swift
//  Sourced
//
//  List of available brands for user selection
//

import Foundation

let availableBrands = [
    "120% Lino",
    "1901",
    "28 Palms",
    "3.1 Phillip Lim for Target",
    "32 Bar Blues",
    "7 For All Mankind",
    "Abercrombie & Fitch",
    "adidas",
    "Alan Flusser",
    "Alan Paine",
    "Alex Mill",
    "Alexander Julian",
    "Alfani",
    "All Saints",
    "Altea",
    "Amazon Essentials",
    "American Eagle Outfitters",
    "American Rag",
    "Armani Exchange",
    "Artistry In Motion",
    "ASOS",
    "Aspesi",
    "Austin Reed",
    "Baird Mcnutt",
    "Banana Republic",
    "Banana Republic Factory",
    "Banks Journal",
    "Barba",
    "Barbour",
    "Barneys New York",
    "Ben Sherman",
    "Ben Silver",
    "Benson",
    "Bertigo",
    "Billabong",
    "Bills Khakis",
    "Billy Reid",
    "Black Brown 1826",
    "Bloomingdale's",
    "Boden",
    "Boggi Milano",
    "Bohio",
    "Bonobos",
    "Boss",
    "Brioni",
    "Brooks Brothers",
    "Brunello Cucinelli",
    "Bruno",
    "Bugatchi",
    "Burberry",
    "C&C California",
    "Cafe Luna",
    "Calvin Klein",
    "Canali",
    "Carbon2Cobalt",
    "Caribbean",
    "Caribbean Joe",
    "Castaway",
    "Chaps",
    "Charles Tyrwhitt",
    "Charleston Threads",
    "Chico's",
    "Chiragh Apparel",
    "chubbies",
    "Civil Society",
    "Claiborne",
    "Club Monaco",
    "Club Room",
    "Columbia",
    "Coofandy",
    "Corneliani",
    "Corridor",
    "COS",
    "CP Shades",
    "croft & barrow",
    "crown & ivy",
    "Cubavera",
    "Culturata",
    "Dandy Del Mar",
    "Daniel Cremieux",
    "David Donahue",
    "Denim & Flower",
    "Diesel",
    "Disney",
    "Dkny",
    "Eddie Bauer",
    "Elie Tahari",
    "Emporio Armani",
    "Ermenegildo Zegna",
    "Eton",
    "Etro",
    "Even Tide",
    "Express",
    "Faconnable",
    "Faherty",
    "Fairway & Greene",
    "Fat Face",
    "Flax",
    "Folk",
    "Forever 21",
    "Frank & Eileen",
    "Gant",
    "GAP",
    "Geoffrey Beene",
    "Gildan",
    "Giorgio Armani",
    "Gitman Brothers",
    "Good Man Brand",
    "Goodfellow & Co",
    "Goodthreads",
    "Gran Sasso",
    "Grant Thomas",
    "Grayers",
    "Gucci",
    "Guess",
    "H&M",
    "Harmont & Blaine",
    "Hart Schaffner Marx",
    "Hartford",
    "Haupt",
    "Henry Cotton's",
    "Henry Jacobson",
    "Heritage",
    "Hickey Freeman",
    "Hiho",
    "Hollister",
    "Hugo Boss",
    "Hurley",
    "Ike Behar",
    "INC International Concepts",
    "Isaac Mizrahi",
    "Isaia",
    "Island Company",
    "Island Republic",
    "Izod",
    "J. Crew",
    "J. Crew Factory",
    "J. Jill",
    "J. McLaughlin",
    "J. Peterman",
    "Jachs",
    "James Perse",
    "Joe's Jeans",
    "John Blair",
    "John Varvatos",
    "johnnie-O",
    "Johnston & Murphy",
    "Jos. A. Bank",
    "Joseph Abboud",
    "Katin",
    "Kenneth Cole",
    "Kenny Flowers",
    "Kiton",
    "L.L. Bean",
    "Lacoste",
    "Lands' End",
    "Lauren Ralph Lauren",
    "LEDBURY",
    "Lee",
    "Levi's",
    "Lilly Pulitzer",
    "Liz Claiborne",
    "Loro Piana",
    "Luca Faloni",
    "Luciano Barbera",
    "Lucky Brand",
    "lululemon athletica",
    "Maceoo",
    "Madewell",
    "Magaschoni",
    "Mango",
    "Marc Anthony",
    "Marc Jacobs",
    "Margaritaville",
    "Marine Layer",
    "Martin Gordon",
    "Massimo Dutti",
    "Merona",
    "Michael Kors",
    "MICHAEL Michael Kors",
    "mine",
    "Modern Amusement",
    "Mr. Turk",
    "Murano",
    "Nat Nast",
    "Nautica",
    "Neiman Marcus",
    "Nike",
    "Nordstrom",
    "North Sails",
    "Oak Hill",
    "Ocean + Coast",
    "Old Navy",
    "OndadeMar",
    "Onia",
    "Original Penguin",
    "Original Use",
    "Original Weatherproof Vintage",
    "Orlebar Brown",
    "Orvis",
    "Oscar de la Renta",
    "Outerknown",
    "Outlier",
    "PacSun",
    "Panama Jack",
    "Patagonia",
    "Paul & Shark",
    "Paul Fredrick",
    "Paul Smith",
    "Paul Stuart",
    "Peloton",
    "Pendleton",
    "Perry Ellis",
    "Peter Millar",
    "Pink House",
    "PINK Victoria's Secret",
    "Polo Ralph Lauren",
    "Porter & Ash",
    "Primark",
    "Pronto Uomo",
    "Proper Cloth",
    "Psycho Bunny",
    "Raffi",
    "rag & bone",
    "Rails",
    "Ralph Lauren",
    "Ralph Lauren Blue Label",
    "Ralph Lauren Double RL",
    "Ralph Lauren Purple Label",
    "Reiss",
    "Report Collection",
    "reyn spooner",
    "Roark",
    "Robert Graham",
    "Robert Talbott",
    "Rodd & Gunn",
    "Roundtree & Yorke",
    "RVCA",
    "Saddlebred",
    "Saddlebrook",
    "Saks Fifth Avenue",
    "Saks Fifth Avenue Black Label",
    "Sandro",
    "Scotch & Soda",
    "Scott Barber",
    "Scott James",
    "Sean John",
    "SHEIN",
    "Sid Mashburn",
    "SOLID & STRIPED",
    "Sonoma",
    "Southern Tide",
    "Spier & Mackay",
    "St. John's Bay",
    "Stafford",
    "Stitch Note",
    "Stone Rose",
    "Suitsupply",
    "Sun + Stone",
    "Swims",
    "Tailor Vintage",
    "Tailorbyrd",
    "TALLIA",
    "Tasso Elba",
    "Taylor Stitch",
    "Ted Baker",
    "Ted Baker London",
    "The Men's Store",
    "The Territory Ahead",
    "Theory",
    "Thomas Dean",
    "Thomas Pink",
    "Todd Snyder",
    "Tombolo",
    "Tommy Bahama",
    "Tommy Hilfiger",
    "Tori Richard",
    "Toscano",
    "True Grit",
    "Trust",
    "Twillory",
    "Under Armour",
    "Uniqlo",
    "United Colors Of Benetton",
    "UNTUCKit",
    "Urban Outfitters",
    "Van Heusen",
    "Vans",
    "Velvet by Graham & Spencer",
    "Versace",
    "Vilebrequin",
    "Vince",
    "Vineyard Vines",
    "Vintage",
    "Vstr",
    "Weatherproof",
    "Weekenders",
    "William Murray Golf",
    "Zachary Prell",
    "Zara"
]
